/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemontiRouteImport } from './routes/remonti'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as GtpRouteImport } from './routes/gtp'
import { Route as GazRouteImport } from './routes/gaz'
import { Route as IndexRouteImport } from './routes/index'

const RemontiRoute = RemontiRouteImport.update({
  id: '/remonti',
  path: '/remonti',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const GtpRoute = GtpRouteImport.update({
  id: '/gtp',
  path: '/gtp',
  getParentRoute: () => rootRouteImport,
} as any)
const GazRoute = GazRouteImport.update({
  id: '/gaz',
  path: '/gaz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gaz': typeof GazRoute
  '/gtp': typeof GtpRoute
  '/kontakti': typeof KontaktiRoute
  '/remonti': typeof RemontiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gaz': typeof GazRoute
  '/gtp': typeof GtpRoute
  '/kontakti': typeof KontaktiRoute
  '/remonti': typeof RemontiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gaz': typeof GazRoute
  '/gtp': typeof GtpRoute
  '/kontakti': typeof KontaktiRoute
  '/remonti': typeof RemontiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gaz' | '/gtp' | '/kontakti' | '/remonti'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gaz' | '/gtp' | '/kontakti' | '/remonti'
  id: '__root__' | '/' | '/gaz' | '/gtp' | '/kontakti' | '/remonti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GazRoute: typeof GazRoute
  GtpRoute: typeof GtpRoute
  KontaktiRoute: typeof KontaktiRoute
  RemontiRoute: typeof RemontiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/remonti': {
      id: '/remonti'
      path: '/remonti'
      fullPath: '/remonti'
      preLoaderRoute: typeof RemontiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtp': {
      id: '/gtp'
      path: '/gtp'
      fullPath: '/gtp'
      preLoaderRoute: typeof GtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaz': {
      id: '/gaz'
      path: '/gaz'
      fullPath: '/gaz'
      preLoaderRoute: typeof GazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GazRoute: GazRoute,
  GtpRoute: GtpRoute,
  KontaktiRoute: KontaktiRoute,
  RemontiRoute: RemontiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
